### PR TITLE
it's a sekrit

### PR DESCRIPTION
**Pull request by kirjavascript**
dongers

### CODE REVIEW

**Comment by sector-f** [comment]
Good start! I found some stuff that needs changed though:

This stuff?

```rust
#[link(name = "virt")]
extern "C" {
    fn virSecretGetName(ptr: sys::virSecretPtr) -> *const libc::c_char;
}

/* ... */

pub fn get_name(&self) -> Result<String, Error> {
    unsafe {
        let n = virSecretGetName(self.as_ptr());
        if n.is_null() {
            return Err(Error::last_error());
        }
        return Ok(c_chars_to_string!(n));
    }
}

```

Yeah I'm pretty sure that needs removed completely. It's in the original `virt` crate, but...I honestly don't know why.  [Here](https://libvirt.org/html/libvirt-libvirt-secret.html) is the API docs for libvirt-secret. [Here](https://libvirt.org/hvsupport.html) is the libvirt API support matrix. I can find *nothing* indicating that `virSecretGetName` exists. I even googled "virSecretGetName"; I got two results: One is virt's secret.rs file on docs.rs and the other is virt's secret.rs on github.

And now for some less weird stuff:

* According to the docs for [virSecretDefineXML](https://libvirt.org/html/libvirt-libvirt-secret.html#virSecretDefineXML), the `flags` argument isn't actually used. So just remove that argument from `define_xml()` and pass 0 within that function. It looks like this also applies to `get_value()` and `set_value()`

* You should add a thing to `flags` for [virSecretUsageType](https://libvirt.org/html/libvirt-libvirt-secret.html#virSecretUsageType); this should be what gets passed to `lookup_by_usage()` and returned by `get_usage_type()`

**Comment by kirjavascript** [comment]
the link for virSecretUsageType's enum lists it as cardinals but I changed it to powers of two as that seems to be the convention. dunno if changing the flags will break anything

**Comment by sector-f** [comment]
Yes, changing the flags will break things. The other functions are using the enum as a bitmask, so you do a bitwise OR operation to pass multiple values. This one is apparently just expecting a single value to be passed. Change SecretGetUsageType to match https://libvirt.org/html/libvirt-libvirt-secret.html#virSecretUsageType

Also, it should be i32 since the function that returns it returns int rather than uint.

**Comment by kirjavascript** [comment]
🍋

**Pull request merged**
